import "./InfoPages.css";

function Terms() {
    return (
        <div className="info-page">

            <div className="info-hero compact">

                <span className="info-kicker">
                    GROWELL AI
                </span>

                <h1>
                    Terms of Use
                </h1>

                <p>
                    Please read these terms before using GroWell AI.
                </p>

            </div>


            <div className="info-section">

                <h2>1. Acceptance of Terms</h2>

                <p>
                    By accessing or using GroWell AI, you agree to
                    these Terms of Use. If you do not agree with these
                    terms, please do not use the platform.
                </p>

            </div>


            <div className="info-section">

                <h2>2. Purpose of GroWell AI</h2>

                <p>
                    GroWell AI provides AI-assisted agricultural
                    information, analysis and decision-support
                    features.
                </p>

                <p>
                    The platform is intended to assist farmers and
                    agricultural users with information related to
                    crops, soil, weather, plant health and farming
                    practices.
                </p>

            </div>


            <div className="info-section">

                <h2>3. Agricultural Information</h2>

                <p>
                    Information generated by GroWell AI is intended
                    to serve as decision-support information and
                    should not automatically be treated as a
                    guaranteed agricultural prescription.
                </p>

                <p>
                    Agricultural conditions vary according to
                    location, soil, crop variety, climate, farming
                    practices and other factors.
                </p>

            </div>


            <div className="info-section">

                <h2>4. AI-Generated Results</h2>

                <p>
                    GroWell AI uses artificial intelligence to
                    generate responses and recommendations.
                </p>

                <p>
                    AI-generated information may occasionally be
                    incomplete, inaccurate or unsuitable for a
                    specific field condition.
                </p>

            </div>


            <div className="info-section">

                <h2>5. User Responsibility</h2>

                <p>
                    Users are responsible for evaluating information
                    provided by GroWell AI before applying it to
                    agricultural activities.
                </p>

                <p>
                    Users should consider local agricultural
                    recommendations and professional agricultural
                    advice when making important farming decisions.
                </p>

            </div>


            <div className="info-section">

                <h2>6. Prohibited Use</h2>

                <ul className="info-list">

                    <li>
                        Do not misuse or attempt to disrupt the
                        GroWell AI platform.
                    </li>

                    <li>
                        Do not attempt to gain unauthorized access
                        to the platform or its systems.
                    </li>

                    <li>
                        Do not use GroWell AI for unlawful purposes.
                    </li>

                    <li>
                        Do not intentionally submit malicious
                        content or harmful files.
                    </li>

                </ul>

            </div>


            <div className="info-section">

                <h2>7. GroWell Premium Subscription</h2>

                <p>
                    Some GroWell AI features are provided under a
                    paid monthly subscription called GroWell Premium.
                    The current price is shown on the upgrade page
                    before you subscribe.
                </p>

                <p>
                    Premium is billed monthly in Indian Rupees
                    through Razorpay by UPI, netbanking or card. The
                    subscription renews automatically each month
                    until you cancel it. We do not see or store your
                    card or UPI details.
                </p>

                <p>
                    You can cancel at any time from Settings, under
                    Plan &amp; Billing. Cancellation stops future
                    renewals. You keep full access to Premium until
                    the end of the period you have already paid for,
                    and your account then returns to the free tier.
                </p>

                <p>
                    If a renewal payment fails, Premium may pause
                    until payment is resolved. We will attempt to
                    notify you.
                </p>

                <p>
                    Payments are processed by Razorpay. Fees charged
                    by your bank or payment provider are your
                    responsibility. Refunds are handled according to
                    our refund policy and the applicable law.
                </p>

            </div>


            <div className="info-section">

                <h2>8. Acceptable Use of Premium</h2>

                <p>
                    Premium is licensed to one individual or farming
                    household. Automated scraping, reselling,
                    credential sharing, or using GroWell AI to build a
                    competing commercial service is not permitted.
                    We may suspend a paid account that misuses the
                    service.
                </p>

            </div>


            <div className="info-section">

                <h2>9. Changes to the Platform</h2>

                <p>
                    GroWell AI may be updated, modified or expanded
                    as the platform develops. Features included in
                    Premium may change. If a change materially
                    reduces the value of a paid subscription, we
                    will give notice before it takes effect.
                </p>

            </div>


            <div className="info-section">

                <h2>10. Changes to These Terms</h2>

                <p>
                    These Terms of Use may be updated as GroWell AI
                    evolves. Continued use of the platform after
                    changes are published constitutes acceptance of
                    the updated terms.
                </p>

            </div>


            <div className="info-bottom">

                <strong>
                    GroWell AI
                </strong>

                <span>
                    Agricultural intelligence for better decisions.
                </span>

            </div>

        </div>
    );
}

export default Terms;