import "./InfoPages.css";

function Terms() {
    return (
        <div className="info-page">

            <div className="info-hero compact">

                <span className="info-kicker">
                    GROWELL AI
                </span>

                <h1>
                    Terms of Use
                </h1>

                <p>
                    Please read these terms before using GroWell AI.
                </p>

            </div>


            <div className="info-section">

                <h2>1. Acceptance of Terms</h2>

                <p>
                    By accessing or using GroWell AI, you agree to
                    these Terms of Use. If you do not agree with these
                    terms, please do not use the platform.
                </p>

            </div>


            <div className="info-section">

                <h2>2. Purpose of GroWell AI</h2>

                <p>
                    GroWell AI provides AI-assisted agricultural
                    information, analysis and decision-support
                    features.
                </p>

                <p>
                    The platform is intended to assist farmers and
                    agricultural users with information related to
                    crops, soil, weather, plant health and farming
                    practices.
                </p>

            </div>


            <div className="info-section">

                <h2>3. Agricultural Information</h2>

                <p>
                    Information generated by GroWell AI is intended
                    to serve as decision-support information and
                    should not automatically be treated as a
                    guaranteed agricultural prescription.
                </p>

                <p>
                    Agricultural conditions vary according to
                    location, soil, crop variety, climate, farming
                    practices and other factors.
                </p>

            </div>


            <div className="info-section">

                <h2>4. AI-Generated Results</h2>

                <p>
                    GroWell AI uses artificial intelligence to
                    generate responses and recommendations.
                </p>

                <p>
                    AI-generated information may occasionally be
                    incomplete, inaccurate or unsuitable for a
                    specific field condition.
                </p>

            </div>


            <div className="info-section">

                <h2>5. User Responsibility</h2>

                <p>
                    Users are responsible for evaluating information
                    provided by GroWell AI before applying it to
                    agricultural activities.
                </p>

                <p>
                    Users should consider local agricultural
                    recommendations and professional agricultural
                    advice when making important farming decisions.
                </p>

            </div>


            <div className="info-section">

                <h2>6. Prohibited Use</h2>

                <ul className="info-list">

                    <li>
                        Do not misuse or attempt to disrupt the
                        GroWell AI platform.
                    </li>

                    <li>
                        Do not attempt to gain unauthorized access
                        to the platform or its systems.
                    </li>

                    <li>
                        Do not use GroWell AI for unlawful purposes.
                    </li>

                    <li>
                        Do not intentionally submit malicious
                        content or harmful files.
                    </li>

                </ul>

            </div>


            <div className="info-section">

                <h2>7. Changes to the Platform</h2>

                <p>
                    GroWell AI may be updated, modified or expanded
                    as the platform develops.
                </p>

            </div>


            <div className="info-section">

                <h2>8. Changes to These Terms</h2>

                <p>
                    These Terms of Use may be updated as GroWell AI
                    evolves. Continued use of the platform after
                    changes are published constitutes acceptance of
                    the updated terms.
                </p>

            </div>


            <div className="info-bottom">

                <strong>
                    GroWell AI
                </strong>

                <span>
                    Agricultural intelligence for better decisions.
                </span>

            </div>

        </div>
    );
}

export default Terms;